In [5]:
# Python program to add two matrices
from sympy import Matrix
import numpy as np
# Utility function to add matrices using for loop
def add_matrix_for(X, Y, result, len_x, len_y):
    # iterate over loop and add elements
    for i in range(len_x):
        for j in range(len_y):
            result[i][j] = X[i][j] + Y[i][j]
    # print added result matrix
    for k in result:
        print(k)

# Utility function to add matrices using list comprehension
def add_matrix_list(X, Y, len_x, len_y):
    result_list = [[X[i][j] + Y[i][j] for j in range(len_y)] for i in range(len_x)]
    for r in result_list:
        print(r)

# Utility function to add matrices using zip function
def add_matrix_zip(X, Y):
    result = [map(sum, zip(*t)) for t in zip(X, Y)]
    print(result)

# Utility function to add matrices using numpy arrays and +
def add_matrix_numpy_arr(X, Y):
    result =  np.array(X) + np.array(Y)
    print(result)
    
# Utility function to add matrices using Matrix class from sympy library
def add_matrix_sympy_matrix(X, Y):
    result = Matrix(X) + Matrix(Y)
    print(result)
    

# inputs
X = [[1,2,3],
     [4,5,6],
     [2,4,6]]

Y = [[3,5,7],
     [7,2,9],
     [1,0,3]]

result = [[0,0,0],
          [0,0,0],
          [0,0,0]]

len_x = len(X)
len_y = len(X[0])

# call functions
add_matrix_for(X, Y, result, len_x, len_y)
add_matrix_list(X, Y, len_x, len_y)
add_matrix_zip(X, Y)
add_matrix_numpy_arr(X, Y)
add_matrix_sympy_matrix(X, Y)

[4, 7, 10]
[11, 7, 15]
[3, 4, 9]
[4, 7, 10]
[11, 7, 15]
[3, 4, 9]
[<map object at 0x7f9d5af041c0>, <map object at 0x7f9d5af04250>, <map object at 0x7f9d5af042e0>]
[[ 4  7 10]
 [11  7 15]
 [ 3  4  9]]
Matrix([[4, 7, 10], [11, 7, 15], [3, 4, 9]])


In [6]:
# Python program to multiply two matrices

A = [[1, 2, 3, 4],
     [4, 5, 6, 7],
     [3, 4, 5, 6]]

B = [[3, 2],
     [4, 3],
     [6, 7],
     [2, 6]]

res = np.dot(A, B)

for i in res:
    print(i)

[37 53]
[ 82 107]
[67 89]


In [7]:
# Python program for matrix product

# initializing list
matrix_list = [[1, 2, 3], [4, 5, 6], [1, 7, 5]]

res = 1
for i in matrix_list:
    for j in i:
        res *= j

# printing result        
print("Product of all the elements in the list is: ", res)        

Product of all the elements in the list is:  25200


In [8]:
# Adding and Subtracting Matrices in Python

# Inititalizing matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 6], [4, 3]])

print("Addition of two matrices :", np.add(A, B))
print()
print("Subtraction of two matrices :", np.subtract(A, B))

Addition of two matrices : [[5 8]
 [7 7]]

Subtraction of two matrices : [[-3 -4]
 [-1  1]]


In [11]:
# Python program for Transpose of a matrix in a single line

# Creating matrix
C = [[2, 3], 
     [4, 5]]

D = np.transpose(C)
print("Transpose matrix for given matrix is :", D)
print()

# another way
print("Transpose matrix for given matrix is :", np.array(C).T)

Transpose matrix for given matrix is : [[2 4]
 [3 5]]

Transpose matrix for given matrix is : [[2 4]
 [3 5]]


In [13]:
# Python program for matrix creation of n*n

#Dimension initialization
N = 5

res = []
for i in range(N):
    row = []
    for j in range(N):
        row.append(1 + N * i + j)
    res.append(row)
    
print("matrix of dimension ", N, "is :", res)    

matrix of dimension  5 is : [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]


In [21]:
# Python program for getting Kth column of matrix

# Initializing values
A = np.array([[1, 2, 3, 4, 5, 6],
              [7, 8, 9, 0, 1, 2],
              [3, 4, 5, 6, 7, 8]])

K = 4

# Using list slicing
r = [row[K] for row in A]

print(K, "th column in matrix is :", r)

# another way
print(K, "th column using slicing is :", A[:,K])

4 th column in matrix is : [5, 1, 7]
4 th column using slicing is : [5 1 7]


In [26]:
# Python program for vertical concatenation of string matrix
from itertools import zip_longest

test_list = [["Today", "is", "a", "good", "day"],
             ["ab", "cd", "ef", "is", "at"]]

v_list = ["".join(elem) for elem in zip_longest(*test_list, fillvalue="")]

print("Vertical concatenation of given string matrix :", v_list)

Vertical concatenation of given string matrix : ['Todayab', 'iscd', 'aef', 'goodis', 'dayat']
